package edu.nyu.dtl.synner.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Date;

@DynamoDBTable(tableName="DownloadContacts")
public class DownloadContact {

    public String id;

    public Date time;

    @JsonProperty
    public String name;

    @JsonProperty
    public String surname;

    @JsonProperty
    public String email;

    @JsonProperty
    public String organization;

    @JsonProperty
    public String comments;

    public DownloadContact() {
        this.time = new Date();
    }

    public DownloadContact(String name, String surname, String email, String organization, String comments) {
        this.time = new Date();
        this.name = name;
        this.surname = surname;
        this.email = email;
        this.organization = organization;
        this.comments = comments;
    }

    @DynamoDBHashKey(attributeName="ID")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName="time")
    public Date getTime() {
        return time;
    }
    public void setTime(Date time) {
        this.time = time;
    }

    @DynamoDBAttribute(attributeName="name")
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute(attributeName="surname")
    public String getSurname() {
        return surname;
    }
    public void setSurname(String surname) {
        this.surname = surname;
    }

    @DynamoDBAttribute(attributeName="email")
    public String getEmail() {
        return email;
    }
    public void setEmail(String email) {
        this.email = email;
    }

    @DynamoDBAttribute(attributeName="organization")
    public String getOrganization() {
        return organization;
    }
    public void setOrganization(String organization) {
        this.organization = organization;
    }

    @DynamoDBAttribute(attributeName="comments")
    public String getComments() {
        return comments;
    }
    public void setComments(String comments) {
        this.comments = comments;
    }

}
